In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
all_data = pd.read_csv("light_dark_font_training_set.csv")
all_inputs = (all_data.iloc[:,0:3].values /255.0)
all_outputs = all_data.iloc[:,-1].valuess

      RED  GREEN  BLUE  LIGHT_OR_DARK_FONT_IND
0       0      0     0                       1
1       0      0   128                       1
2       0      0   139                       1
3       0      0   205                       1
4       0      0   238                       1
...   ...    ...   ...                     ...
1340   95    158   160                       0
1341   96    123   139                       1
1342   97     97    97                       1
1343   99    184   255                       0
1344   99     99    99                       1

[1345 rows x 4 columns]
[[0.         0.         0.        ]
 [0.         0.         0.50196078]
 [0.         0.         0.54509804]
 ...
 [0.38039216 0.38039216 0.38039216]
 [0.38823529 0.72156863 1.        ]
 [0.38823529 0.38823529 0.38823529]]
