In [4]:
import numpy as np

# Define a 3x3 matrix
A = np.array([[12, -51, 4], 
              [6, 167, -68], 
              [-4, 24, -41]])
# Perform QR Decomposition
Q, R = np.linalg.qr(A)

print("Q (Orthogonal Matrix):\n", Q)
print("\nR (Upper Triangular Matrix):\n", R)

Q (Orthogonal Matrix):
 [[-0.85714286  0.39428571  0.33142857]
 [-0.42857143 -0.90285714 -0.03428571]
 [ 0.28571429 -0.17142857  0.94285714]]

R (Upper Triangular Matrix):
 [[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]


In [3]:
import numpy as np

# Define a 3x3 matrix
ssa = np.array([[1, 1, 1], 
              [1, 1, 1], 
              [1, 1, 1]])
# Perform QR Decomposition
Q, R = np.linalg.qr(ssa)

print("Q (Orthogonal Matrix):\n", Q)
print("\nR (Upper Triangular Matrix):\n", R)

Q (Orthogonal Matrix):
 [[-0.57735027 -0.57735027 -0.57735027]
 [-0.57735027  0.78867513 -0.21132487]
 [-0.57735027 -0.21132487  0.78867513]]

R (Upper Triangular Matrix):
 [[-1.73205081 -1.73205081 -1.73205081]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
